# Default initial positions for robotic_arm's ros2_control fake system

initial_positions:
  arm_elbow_joint: 0
  base_shoulder_joint: 0
  elbow_forearm_joint: 0
  forearm_wrist_joint: 0
  gripper_base_left_joint: 0
  shoulder_arm_joint: 0
  wrist_hand_joint: 0